export const INDONESIAN_CITIES = [
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Timur",
  "Bekasi",
  "Tangerang",
  "Tangerang Selatan",
  "Depok",
  "Bogor",
  "Surabaya",
  "Bandung",
  "Medan",
  "Semarang",
  "Makassar",
  "Palembang",
  "Yogyakarta",
  "Solo",
  "Malang",
  "Padang",
  "Pekanbaru",
  "Makassar",
  "Samarinda",
  "Banjarmasin",
  "Denpasar",
  "Lombok",
  "Manado",
  "Pontianak",
  "Cirebon",
  "Tasikmalaya",
  "Sukabumi",
  "Karawang",
  "Serang",
  "Cilegon",
  "Mataram",
  "Kupang",
  "Jayapura",
  "Ambon",
  "Palu",
  "Kendari",
  "Goru",
  "Tomohon",
  "Batu",
  "Blitar",
  "Kediri",
  "Madiun",
  "Pasuruan",
  "Probolinggo",
  "Jember",
  "Banyuwangi",
  "Situbondo",
  "Bondowoso",
  "Ponorogo",
  "Trenggalek",
  "Tulungagung",
  "Bojonegoro",
  "Nganjuk",
  "Ngawi",
  "Magetan",
  "Pacitan",
  "Lumajang",
  "Probolinggo",
  "Sleman",
  "Bantul",
  "Gunung Kidul",
  "Kulon Progo",
];
