const RAW_CITIES: string[] = [
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Utara",
  "Jakarta Barat",
  "Jakarta Timur",
  "Bekasi",
  "Tangerang",
  "Tangerang Selatan",
  "Depok",
  "Bogor",
  "Surabaya",
  "Bandung",
  "Medan",
  "Semarang",
  "Makassar",
  "Palembang",
  "Yogyakarta",
  "Solo",
  "Malang",
  "Padang",
  "Pekanbaru",
  "Samarinda",
  "Banjarmasin",
  "Denpasar",
  "Lombok",
  "Manado",
  "Pontianak",
  "Cirebon",
  "Tasikmalaya",
  "Sukabumi",
  "Karawang",
  "Serang",
  "Cilegon",
  "Mataram",
  "Kupang",
  "Jayapura",
  "Ambon",
  "Palu",
  "Kendari",
  "Gorontalo",
  "Tomohon",
  "Batu",
  "Blitar",
  "Kediri",
  "Madiun",
  "Pasuruan",
  "Probolinggo",
  "Jember",
  "Banyuwangi",
  "Situbondo",
  "Bondowoso",
  "Ponorogo",
  "Trenggalek",
  "Tulungagung",
  "Bojonegoro",
  "Nganjuk",
  "Ngawi",
  "Magetan",
  "Pacitan",
  "Lumajang",
  "Sleman",
  "Bantul",
  "Gunung Kidul",
  "Kulon Progo",
]

const seen = new Set<string>()
export const INDONESIAN_CITIES: string[] = RAW_CITIES.filter((c) => {
  const slug = c.toLowerCase().replace(/\s+/g, '-')
  if (seen.has(slug)) {
    console.warn(`[cities] Duplicate entry removed: ${c}`)
    return false
  }
  seen.add(slug)
  return true
})